name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    name: Validate module
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          version: 1.8

      - name: Run tofu init
        id: init
        run: tofu init -upgrade

      - name: Run tofu validate
        run: tofu validate

  validate-example:
    name: Validate example
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          version: 1.8

      - name: Run tofu init on example
        id: init
        run: |
          cd examples/simple
          tofu init -upgrade

      - name: Run tofu validate on example
        run: |
          cd examples/simple
          tofu validate
